name: SOOS GitHub Actions

# Controls when the workflow will run
on: [push]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
    name: SOOS DAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SOOS SCA Analysis
        uses: soos-io/soos-sca-github-action@pre-release-testing
        with:
          project_name: ${{ github.repository }}
          sarif: "true"
          api_url: "https://qa-api.soos.io/api/"
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
      - name: Upload SOOS SCA Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
